### ISSUE TITLE
Container component isn't available through reapp-kit

### ISSUE THREAD

**Issue by miyamotodev123** [reapp/reapp-kit#1]
I'm trying to render a container component by importing it through the reapp-kit but when I try to render there is a Uncaught TypeError: Cannot read property 'toUpperCase' of undefined. I looked through the reapp-ui code and it lists Container as an available component so not too sure why it's not working with reapp-kit. Is there any way to use the Container component and the grid system with reapp? 

my code: 

``` javascript
import { 
  React, 
  View,
  Button,
  Container
} from 'reapp-kit';

export default class extends React.Component {
  render() {
    return (
      <View
        {...this.props}
        title="Container">

        <Container>
          <Button>some button</Button>
        </Container>
      </View>
    );
  }
}
```

**Comment by natew** [comment]
Sorry, the docs are out of date. I'm going to work on updating them soon. It's been moved into Grid. Grid.Container

**Comment by miyamotodev123** [comment]
Ok thanks! The Grid.Container works now, I have two buttons in a container but they aren't spread out evenly. I'm excited for the updated docs but in the meantime I'll just use custom styles with flexbox on some divs to spread elements out the way I want. Let me know if I can help you out with the docs in any way. We were using React-Native but got interested in Reapp since it works for android too.

**Comment by natew** [comment]
Added this to the latest reapp-ui, if you reinstall reapp-kit just plain Container should work as well.
